/* GENERATED by scripts/build-lexicon.mjs from brand/verbal/concepts.md + messaging.md. Do not edit. */
window.MEDDLE_LEXICON = {
 "rules": [
  {
   "level": "error",
   "term": "agency",
   "instead": "studio",
   "why": "We're the alternative to the agency model. \"Traditional agency\" is allowed only as the named foil in comparisons.",
   "source": "\\bagency\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "disrupt*",
   "instead": "challenger, interfere with the status quo",
   "why": "Overused, and \"interfere\" is literally our name.",
   "source": "\\bdisrupt[\\w-]*",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "synerg*",
   "instead": "(say the actual benefit)",
   "why": "Empty.",
   "source": "\\bsynerg[\\w-]*",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "leverag*",
   "instead": "use, build on",
   "why": "Jargon.",
   "source": "\\bleverag[\\w-]*",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "best-in-class",
   "instead": "exceptional, or prove it with a result",
   "why": "Unprovable superlatives.",
   "source": "\\bbest-in-class\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "world-class",
   "instead": "exceptional, or prove it with a result",
   "why": "Unprovable superlatives.",
   "source": "\\bworld-class\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "cutting-edge",
   "instead": "modern, or name the specific thing",
   "why": "Cliché.",
   "source": "\\bcutting-edge\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "bleeding-edge",
   "instead": "modern, or name the specific thing",
   "why": "Cliché.",
   "source": "\\bbleeding-edge\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "elevate your brand",
   "instead": "(name the business outcome)",
   "why": "Agency filler. Use it only in the mission statement, where it's already approved.",
   "source": "\\belevate\\s+your\\s+brand\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "seamless",
   "instead": "(describe what actually happens)",
   "why": "Says nothing.",
   "source": "\\bseamless\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "seamlessly",
   "instead": "(describe what actually happens)",
   "why": "Says nothing.",
   "source": "\\bseamlessly\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "game-chang*",
   "instead": "(show the change)",
   "why": "Cliché.",
   "source": "\\bgame-chang[\\w-]*",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "passionate",
   "instead": "(show it through specifics)",
   "why": "Everyone says it. Nobody believes it.",
   "source": "\\bpassionate\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "boutique",
   "instead": "founder-led, studio",
   "why": "That's how we describe competitors in the business plan, and it sounds small.",
   "source": "\\bboutique\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "rockstar",
   "instead": "senior, or the actual role",
   "why": "Unserious in the wrong way.",
   "source": "\\brockstar\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "ninja",
   "instead": "senior, or the actual role",
   "why": "Unserious in the wrong way.",
   "source": "\\bninja\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "guru",
   "instead": "senior, or the actual role",
   "why": "Unserious in the wrong way.",
   "source": "\\bguru\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "solutions provider",
   "instead": "studio, partner",
   "why": "Faceless.",
   "source": "\\bsolutions\\s+provider\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "tailored to your unique needs",
   "instead": "(be specific about scope)",
   "why": "Mystery-pricing language.",
   "source": "\\btailored\\s+to\\s+your\\s+unique\\s+needs\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "tailored to your needs",
   "instead": "(be specific about scope)",
   "why": "Mystery-pricing language.",
   "source": "\\btailored\\s+to\\s+your\\s+needs\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "custom quote",
   "instead": "a clear price, or \"engagements start at $30K\"",
   "why": "The opposite of showing our cards.",
   "source": "\\bcustom\\s+quote\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "competitive pricing",
   "instead": "flat fee, one clear price",
   "why": "Vague, and it sounds like a discount.",
   "source": "\\bcompetitive\\s+pricing\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "contact us",
   "instead": "Book an intro call",
   "why": "One CTA, said the same way everywhere.",
   "source": "\\bcontact\\s+us\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "in today's fast-paced world",
   "instead": "(cut it)",
   "why": "A throat-clearing opener.",
   "source": "\\bin\\s+today's\\s+fast-paced\\s+world\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "ever-evolving landscape",
   "instead": "(cut it)",
   "why": "A throat-clearing opener.",
   "source": "\\bever-evolving\\s+landscape\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "excited to announce",
   "instead": "(lead with the news)",
   "why": "Weak LinkedIn opener.",
   "source": "\\bexcited\\s+to\\s+announce\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "excited to share",
   "instead": "(lead with the news)",
   "why": "Weak LinkedIn opener.",
   "source": "\\bexcited\\s+to\\s+share\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "thrilled to announce",
   "instead": "(lead with the news)",
   "why": "Weak LinkedIn opener.",
   "source": "\\bthrilled\\s+to\\s+announce\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "thrilled to share",
   "instead": "(lead with the news)",
   "why": "Weak LinkedIn opener.",
   "source": "\\bthrilled\\s+to\\s+share\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "pleased to announce",
   "instead": "(lead with the news)",
   "why": "Weak LinkedIn opener.",
   "source": "\\bpleased\\s+to\\s+announce\\b",
   "flags": "gi"
  },
  {
   "level": "error",
   "term": "rush job",
   "instead": "fast, two weeks",
   "why": "We're fast, never rushed.",
   "source": "\\brush\\s+job\\b",
   "flags": "gi"
  },
  {
   "level": "warn",
   "term": "startups",
   "instead": "industry challengers, companies",
   "why": "Allowed only for Brand Sprints fit (\"Best for early-stage startups…\"). Everywhere else our audience is challengers, and many are mature companies.",
   "source": "\\bstartups\\b",
   "flags": "gi"
  },
  {
   "level": "warn",
   "term": "startup",
   "instead": "industry challengers, companies",
   "why": "Allowed only for Brand Sprints fit (\"Best for early-stage startups…\"). Everywhere else our audience is challengers, and many are mature companies.",
   "source": "\\bstartup\\b",
   "flags": "gi"
  },
  {
   "level": "warn",
   "term": "branding",
   "instead": "brand strategy, visual identity, brand",
   "why": "Allowed in the core belief, and as a plain search term in page titles and SEO.",
   "source": "\\bbranding\\b",
   "flags": "gi"
  },
  {
   "level": "warn",
   "term": "solutions",
   "instead": "(name the solution)",
   "why": "Allowed only in the core belief and the live \"custom solutions\" line.",
   "source": "\\bsolutions\\b",
   "flags": "gi"
  },
  {
   "level": "warn",
   "term": "elevate",
   "instead": "(name the outcome)",
   "why": "Approved only inside the mission statement.",
   "source": "\\belevate\\b",
   "flags": "gi"
  },
  {
   "level": "warn",
   "term": "get in touch",
   "instead": "Book an intro call",
   "why": "Allowed only as a secondary CTA next to a primary \"Book an intro call\".",
   "source": "\\bget\\s+in\\s+touch\\b",
   "flags": "gi"
  }
 ],
 "allowed": [
  {
   "phrase": "traditional agency",
   "source": "traditional\\s+agency",
   "flags": "gi"
  },
  {
   "phrase": "traditional agencies",
   "source": "traditional\\s+agencies",
   "flags": "gi"
  },
  {
   "phrase": "early-stage startups",
   "source": "early-stage\\s+startups",
   "flags": "gi"
  },
  {
   "phrase": "premium branding",
   "source": "premium\\s+branding",
   "flags": "gi"
  },
  {
   "phrase": "custom solutions",
   "source": "custom\\s+solutions",
   "flags": "gi"
  }
 ],
 "mechanics": [
  {
   "source": "\\$\\d+k\\b",
   "flags": "g",
   "msg": "Money shorthand uses a capital K: $30K"
  },
  {
   "source": "\\$\\d+[kK]?\\s+[-–]\\s+\\$\\d",
   "flags": "g",
   "msg": "Money ranges use an en dash with no spaces: $90K–$250K"
  },
  {
   "source": "\\b\\d+\\s?-\\s?\\d+\\s+(weeks?|months?|days?|hours?|hrs)\\b",
   "flags": "g",
   "msg": "Number ranges use an en dash: 2–3 months"
  },
  {
   "source": "(?<![/#.\\w-])MEDDLE(?![\\w.-])",
   "flags": "g",
   "msg": "Write \"Meddle\" in running text; MEDDLE is only the wordmark"
  },
  {
   "source": "!(?=\\s|$)",
   "flags": "g",
   "msg": "Exclamation point: confidence rarely needs one"
  },
  {
   "source": "\\bFortune favors the daring\\b(?!\\.)",
   "flags": "g",
   "msg": "Sign-off takes a period: Fortune favors the daring."
  },
  {
   "source": "\\p{Emoji_Presentation}",
   "flags": "gu",
   "msg": "Emoji: not in brand copy (the one exception is the ⚡ add-on marker on the site)"
  },
  {
   "source": "(?:#\\w+\\s*){4,}",
   "flags": "g",
   "msg": "Hashtag wall: 0–3 relevant hashtags at most"
  },
  {
   "source": "\\b(Agree|Thoughts|Who else)\\?\\s*$",
   "flags": "gim",
   "msg": "Engagement bait: close with the takeaway, not a question"
  }
 ],
 "lines": [
  "*Fortune favors the daring.*",
  "It's time you seized an *unfair advantage*.",
  "Fast. Cheap. *And* Good.",
  "*All three? At the same time? In THIS economy?*",
  "Complete visual identity in just two weeks, for just $30K.",
  "Two brand options. Detailed deliverables. One unbeatable price.",
  "No guesswork. No haggling. Just impressive work, lightning fast, for one clear price.",
  "Your new site designed in just 2 weeks for $30K."
 ]
};
